version: '3.7'

services:
    redis:
        container_name: chirik_redis
        image: redis:7
        ports:
            - 6379:6379
        environment:
            REDIS_HOST: localhost
            REDIS_PORT: 6379
        volumes:
            - ./redis_data:/data
    postgres:
        container_name: chirik_postgres
        image: postgres:14
        ports:
            - 5432:5432
        environment:
            REDIS_HOST: localhost
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: chirik
        volumes:
            - ./pg_data:/var/lib/postgresql/data
volumes:
    redis:
        driver: local